In [1]:
import numpy as np 
a = [20,30,40,50]

arr = np.array(a)

Now we use append functions

In [2]:
print(np.append(arr,40))

[20 30 40 50 40]


Now we use insert function

In [3]:
print(np.insert(arr,1,78))

[20 78 30 40 50]


Now we use delete function

In [4]:
print(np.delete(arr,1))

[20 40 50]
