In [1]:
import numpy as np 

a = [2,3,4,5,6]

arr = np.array(a)

arr2 = np.array([3,4,5,1,2])

print(arr + arr2)

[5 7 9 6 8]


In [3]:
print(np.add(arr , arr2))

[5 7 9 6 8]


In [4]:
print(arr - arr2)


[-1 -1 -1  4  4]


In [5]:
print(np.subtract(arr,arr2))

[-1 -1 -1  4  4]


In [6]:
print(arr * arr2)

[ 6 12 20  5 12]


In [7]:
print(np.multiply(arr,arr2))

[ 6 12 20  5 12]


In [8]:
print(arr/arr2)

[0.66666667 0.75       0.8        5.         3.        ]


In [ ]:
print(np.divide(arr,arr2))


In [9]:
a = [3,4,5,6,7]
b = [3]

arr = np.array(a)
arr2 = np.array(b)

print(np.power(arr,arr2))

[ 27  64 125 216 343]


In [10]:
print(np.sqrt(arr))

[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [11]:
a = np.sqrt(arr)

a.astype(int)


array([1, 2, 2, 2, 2])