In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

print(a+b)

[1, 2, 3, 4, 2, 3, 4, 5]


In [3]:
import numpy as np 

arr = np.array(a)
arr2 = np.array(b)

print(arr+arr2)

[3 5 7 9]


This is only adding the two functions not concatenating those so we need to use concatenate function for this

In [5]:
print(np.concatenate([arr,arr2]))

[1 2 3 4 2 3 4 5]


Now we will try to concatenate axis wise like horizonatal axis or verticle axis

In [8]:
print(np.concatenate([arr,arr2],axis = 0))

[1 2 3 4 2 3 4 5]


Now lets see the split array 

In [9]:
np.array_split(arr,3)

[array([1, 2]), array([3]), array([4])]