In [1]:
import numpy as np 

a = [23,4,2,1,7,2]

arr = np.array(a)

Now we sort the array


In [2]:
print(np.sort(a))

[ 1  2  2  4  7 23]


Now we search the element in the array

In [4]:
s = np.where(arr == 2)

print(s)

(array([2, 5]),)


In [5]:
s = np.where(arr%2 == 0) # These are the values which are divisible by 2

print(s)

(array([1, 2, 5]),)


Another way of search but in this array must be sorted

In [6]:
s = np.searchsorted(arr,2)

print(s)

4


Now we learn filter


In [7]:
fa = [True,False,True,False,True,False]

new = arr[fa]

print(new)

[23  2  7]


Another way of filter 

In [8]:
fa = arr>3

new = arr[fa]

print(new)

[23  4  7]
